name: Build Font (Windows)

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'  # タグ（v0.0.1 など）で実行

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Extract FontForge (zip)
        run: |
          Expand-Archive -Path .\FontForgeBuilds.zip -DestinationPath C:\FontForge

      - name: Run fontforge script
        run: |
          & "C:\FontForge\FontForgeBuilds\bin\ffpython.exe" .\fontforge_script.py --boxhf --nerd-font --hidden-zenkaku-space

      - name: Run fonttools script
        run: python .\fonttools_script.py

      - name: Zip build folder
        run: Compress-Archive -Path build\* -DestinationPath fontbuild.zip

      - name: Upload to existing GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $tag = "${{ github.ref }}" -replace 'refs/tags/', ''
          gh release upload $tag fontbuild.zip --clobber
        shell: pwsh
